# Uncomment to add libraries
CXXFLAGS += -ggdb -std=c++11 -Wall -Wextra
CXXFLAGS += -I./ -I../deps/plog/include -I../uri_parser -I../light_state_machine
LDFLAGS += -Wall
include ../deps/makefiles/gcc.mak
