# Uncomment to add libraries
LIBRARIES += ../deps/stlplus/containers ../light_state_machine ../state_machine_client
CXXFLAGS += -ggdb -std=c++11 -Wall -Wextra
CXXFLAGS += -I./ -I../deps/plog/include
LDFLAGS += -Wall
include ../deps/makefiles/gcc.mak
